CREATE TABLE CUSTOMER (
    CUSTOMER_ID INTEGER IDENTITY Primary Key,
    NAME VARCHAR(255)
);

CREATE TABLE MOVIE (
    MOVIE_ID INTEGER IDENTITY Primary Key,
    TITLE VARCHAR(255),
    PRICE_CODE TINYINT
);

CREATE TABLE RENTAL (
    RENTAL_ID INTEGER IDENTITY Primary Key,
    MOVIE_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    DAYS_RENTED TINYINT
);

alter table rental add foreign key (MOVIE_ID) references MOVIE(MOVIE_ID);
alter table rental add foreign key (CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID);